import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="overflow-hidden bg-[#fff] text-[#000]"
      >
        <Navbar />
        <Sidebar />
        <div className="bg-gray-100 w-[80%] md:w-[70%] lg:w-[83%] sm:float-right overflow-hidden rounded-xl mt-[5rem]">
        {children}
        </div>
      </body>
    </html>
  );
}
