import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className=" bg-[#fff] text-[#000] overflow-hidden"
      >
        {/* flex w-full gap-[1rem] pt-[3.2rem] md:pt-[4rem] */}
        <Navbar />
          <Sidebar />
          <div className=" w-[80%] md:w-[70%] lg:w-[83%] sm:float-right rounded-xl pt-[5rem] overflow-y-scroll h-screen">
            {children}
          </div>


      </body>
    </html>
  );
}
